FROM mysql:8.0.35
ENV MYSQL_ROOT_PASSWORD=@dmin1
ENV MYSQL_DATABASE=accounts

#Initialize database with backup
ADD db_backup.sql /docker-entrypoint-initdb.d/db_backup.sql

VOLUME ["/var/lib/mysql"]
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 CMD mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD || exit 1
